dist: xenial

language: cpp

env:
  global:
    - SONAR_SCANNER=OFF
    - COVERALLS=OFF
    - RUN_TESTS=ON
    - STOCK_CPPZMQ=ON
    - USE_PCH=ON
    - CMAKE_BUILD_TYPE=Debug
    - TANGO_USE_USING_NAMESPACE=ON
  matrix:
    - OS_TYPE=llvm-latest RUN_TESTS=OFF WARNINGS_AS_ERRORS=ON TANGO_USE_USING_NAMESPACE=OFF USE_PCH=OFF
    - OS_TYPE=gcc-latest RUN_TESTS=OFF WARNINGS_AS_ERRORS=ON TANGO_USE_USING_NAMESPACE=OFF USE_PCH=OFF
    - OS_TYPE=ubuntu-20.04
    - OS_TYPE=debian10
    - OS_TYPE=debian10 USE_PCH=OFF RUN_TESTS=OFF
    - OS_TYPE=debian10 CMAKE_BUILD_TYPE=Release
    - OS_TYPE=debian9
    - OS_TYPE=debian8 SONAR_SCANNER=ON COVERALLS=ON STOCK_CPPZMQ=OFF

notifications:
  email: false

services:
  - docker

addons:
  sonarcloud:
    organization: "tango-controls"
    token: ${SONAR_TOKEN}

before_install:
  - .travis/before_install.sh

before_script:
  - >
      docker build
      --build-arg APP_UID=$(id -u)
      --build-arg APP_GID=$(id -g)
      -t cpp_tango
      .travis/${OS_TYPE}
  - >
      docker run
      --rm
      --name cpp_tango
      -e BINTRAY_API_KEY=${CI_BINTRAY_API_KEY}
      -e BINTRAY_USER_NAME=tango-ci
      -e COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN}
      -e SONAR_TOKEN=${SONAR_TOKEN}
      -e TANGO_HOST=${TANGO_HOST}
      -e TRAVIS_BRANCH=${TRAVIS_BRANCH}
      -e TRAVIS_JOB_ID=${TRAVIS_JOB_ID}
      -v `pwd`:/home/tango/src
      -v `pwd`/idl:/home/tango/idl
      -v `pwd`/cppzmq:/home/tango/cppzmq
      -v `pwd`/tango_admin:/home/tango/tango_admin
      -v `pwd`/coveralls-cmake:/home/tango/coveralls-cmake
      -v `pwd`/build-wrapper-linux-x86:/home/tango/build-wrapper-linux-x86
      -v `pwd`/sonar-scanner:/home/tango/sonar-scanner
      -v /var/run/docker.sock:/var/run/docker.sock
      -dit
      cpp_tango
  - >
      docker exec -u root cpp_tango
      groupadd -g $(grep docker /etc/group | awk -F ':' '{print $3}') dockerhost || true
  - docker exec -u root cpp_tango usermod -a -G dockerhost tango || true
  - .travis/install_tango_idl.sh
  - (test ${STOCK_CPPZMQ} = "OFF" && .travis/install_cppzmq.sh) || true

script:
  - set -e
  - .travis/run.sh
  - .travis/install_tango.sh
  - .travis/install_tango_admin.sh
  - .travis/test.sh
  - set +e

after_success:
  - test ${SONAR_SCANNER} = "ON" && .travis/sonar.sh

deploy:
  - provider: script
    script: bash .travis/deploy.sh
    on:
      tags: true

after-script:
  - docker stop cpp_tango
