dist: trusty
sudo: false

language: cpp

env:
  matrix:
    - OS_TYPE=debian9 CMAKE_BUILD_TYPE=DEBUG SONAR_SCANNER=OFF COVERALLS=OFF
    - OS_TYPE=debian9 CMAKE_BUILD_TYPE=RELEASE SONAR_SCANNER=OFF COVERALLS=OFF
    - OS_TYPE=debian8 CMAKE_BUILD_TYPE=Debug SONAR_SCANNER=ON COVERALLS=ON
    - OS_TYPE=debian8 CMAKE_BUILD_TYPE=RELEASE SONAR_SCANNER=OFF COVERALLS=OFF
    - OS_TYPE=debian7 CMAKE_BUILD_TYPE=RELEASE SONAR_SCANNER=OFF COVERALLS=OFF
#    - OS_TYPE=debian7 CMAKE_BUILD_TYPE=DEBUG
#    - OS_TYPE=win32
# etc

notifications:
  email: false

services:
  - docker

addons:
  sonarcloud:
    organization: "tango-controls"
    token:
      secure: ${SONAR_TOKEN}
  apt:
    update: true

before_install:
  - docker pull tangocs/mysql:9.2.2
  - docker pull tangocs/tango-cs:latest
  - git clone https://github.com/JoakimSoderberg/coveralls-cmake.git
  - git clone -b v4.2.2 https://${CI_USER_TOKEN}@github.com/zeromq/cppzmq.git cppzmq
  - git clone -b tango-9-lts https://${CI_USER_TOKEN}@github.com/tango-controls/tango-idl.git idl
  - sudo apt-get install -y gcovr

before_script:
  - docker run --name mysql_db -e MYSQL_ROOT_PASSWORD=root -d tangocs/mysql:9.2.2 --sql-mode=""
  - CONTAINER=$(docker run --name tango_cs -e TANGO_HOST=127.0.0.1:10000 -e MYSQL_HOST=mysql_db:3306 -e MYSQL_USER=tango -e MYSQL_PASSWORD=tango -e MYSQL_DATABASE=tango --link mysql_db:mysql_db -d tangocs/tango-cs:latest)
  - IPADDR=$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' $CONTAINER)
  - TANGO_HOST=${IPADDR}:10000
  - docker build --build-arg APP_UID=$(id -u) --build-arg APP_GID=$(id -g) -t cpp_tango .travis/${OS_TYPE}
  - docker run --name cpp_tango -e TANGO_HOST=${TANGO_HOST} -e BINTRAY_USER_NAME=tango-ci -e BINTRAY_API_KEY=${CI_BINTRAY_API_KEY} -e COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN} --link tango_cs:tango_cs -v `pwd`:/home/tango/src -v `pwd`/idl:/home/tango/idl -v `pwd`/cppzmq:/home/tango/cppzmq -v `pwd`/coveralls-cmake:/home/tango/coveralls-cmake -dit cpp_tango
  - .travis/install_tango_idl.sh
  - .travis/install_cppzmq.sh

script:
  - .travis/${OS_TYPE}/run.sh
  - .travis/test.sh COVERALLS=OFF

after_success:
  - test ${COVERALLS} = "ON" && gcovr -r `pwd` -x --object-directory=`pwd`/build > report.xml && cat report.xml
  - test ${SONAR_SCANNER} = "ON" && sonar-scanner

deploy:
  - provider: script
    script: bash .travis/deploy.sh
    skip_cleanup: true
    on:
      tags: true

after-script:
  - docker stop cpp_tango
  - docker rm cpp_tango
  - docker stop tango_cs
  - docker rm tango_cs
  - docker stop mysql_db
  - docker rm mysql_db
