dist: xenial

language: cpp

env:
  matrix:
    - OS_TYPE=debian9 CMAKE_BUILD_TYPE=DEBUG SONAR_SCANNER=OFF COVERALLS=OFF
    - OS_TYPE=debian9 CMAKE_BUILD_TYPE=RELEASE SONAR_SCANNER=OFF COVERALLS=OFF
    - OS_TYPE=debian8 CMAKE_BUILD_TYPE=Debug SONAR_SCANNER=ON COVERALLS=ON
    - OS_TYPE=debian8 CMAKE_BUILD_TYPE=RELEASE SONAR_SCANNER=OFF COVERALLS=OFF
    - OS_TYPE=debian7 CMAKE_BUILD_TYPE=RELEASE SONAR_SCANNER=OFF COVERALLS=OFF
#    - OS_TYPE=debian7 CMAKE_BUILD_TYPE=DEBUG
#    - OS_TYPE=win32
# etc

notifications:
  email: false

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
    update: true
  sonarcloud:
    organization: "tango-controls"
    token:
      secure: ${SONAR_TOKEN}

before_install:
  - docker pull tangocs/mysql:9.2.2
  - docker pull tangocs/tango-cs:latest
  - git clone https://github.com/JoakimSoderberg/coveralls-cmake.git
  - git clone -b v4.2.2 https://${CI_USER_TOKEN}@github.com/zeromq/cppzmq.git cppzmq
  - git clone -b tango-9-lts https://${CI_USER_TOKEN}@github.com/tango-controls/tango-idl.git idl
  - wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip && unzip build-wrapper-linux-x86.zip

before_script:
  - >
      docker run
      --rm
      --name mysql_db
      -e MYSQL_ROOT_PASSWORD=root
      -e MYSQL_INITDB_SKIP_TZINFO=1
      -d
      tangocs/mysql:9.2.2
      --sql-mode=""
      --innodb=OFF
      --default-storage-engine=MyISAM
  - >
      docker run
      --rm
      --name mysql_db2
      -e MYSQL_ROOT_PASSWORD=root
      -e MYSQL_INITDB_SKIP_TZINFO=1
      -d
      tangocs/mysql:9.2.2
      --sql-mode=""
      --innodb=OFF
      --default-storage-engine=MyISAM
  - >
      docker run
      --name tango_cs
      -e TANGO_HOST=127.0.0.1:10000
      -e MYSQL_HOST=mysql_db:3306
      -e MYSQL_USER=tango
      -e MYSQL_PASSWORD=tango
      -e MYSQL_DATABASE=tango
      --link mysql_db:mysq_db
      -d
      tangocs/tango-cs:latest
  - >
      docker run
      --name tango_cs2
      -e TANGO_HOST=127.0.0.1:10000
      -e MYSQL_HOST=mysql_db2:3306
      -e MYSQL_USER=tango
      -e MYSQL_PASSWORD=tango
      -e MYSQL_DATABASE=tango
      --link mysql_db2:mysq_db2
      -d
      tangocs/tango-cs:latest
  - sleep 5
  - docker ps -a
  - docker logs tango_cs
  - docker logs tango_cs2
  - TANGO_HOST_IP=$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' tango_cs)
  - TANGO_HOST_IP2=$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' tango_cs2)
  - TANGO_HOST=${TANGO_HOST_IP}:10000
  - docker build --build-arg APP_UID=$(id -u) --build-arg APP_GID=$(id -g) -t cpp_tango .travis/${OS_TYPE}
  - >
      docker run
      --rm
      --name cpp_tango
      -e TANGO_HOST=${TANGO_HOST}
      -e TANGO_HOST2=${TANGO_HOST_IP2}:10000
      -e BINTRAY_USER_NAME=tango-ci
      -e BINTRAY_API_KEY=${CI_BINTRAY_API_KEY}
      -e COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN}
      --link tango_cs
      --link tango_cs2
      -v `pwd`:/home/tango/src
      -v `pwd`/idl:/home/tango/idl
      -v `pwd`/cppzmq:/home/tango/cppzmq
      -v `pwd`/coveralls-cmake:/home/tango/coveralls-cmake
      -v `pwd`/build-wrapper-linux-x86:/home/tango/build-wrapper-linux-x86
      -dit
      cpp_tango
  - .travis/install_tango_idl.sh
  - .travis/install_cppzmq.sh
#work around gcov ignored by sonar
  - sudo mkdir /home/tango && sudo mkdir /home/tango/src && sudo mount --bind `pwd` /home/tango/src

script:
  - .travis/${OS_TYPE}/run.sh
  - .travis/test.sh COVERALLS=OFF

after_success:
  - test ${SONAR_SCANNER} = "ON" && .travis/sonar.sh

deploy:
  - provider: script
    script: bash .travis/deploy.sh
    skip_cleanup: true
    on:
      tags: true

after-script:
  - docker stop cpp_tango
  - docker stop tango_cs tango_cs2
  - docker rm tango_cs tango_cs2
  - docker stop mysql_db mysql_db2
