sudo: false

language: cpp

env:
  matrix:
    - OS_TYPE=debian8 CMAKE_BUILD_TYPE=DEBUG COVERALLS=ON COVERALLS_MODULE_PATH=/home/tango/coveralls-cmake/cmake
    - OS_TYPE=debian8 CMAKE_BUILD_TYPE=RELEASE COVERALLS=OFF
#    - OS_TYPE=debian7 CMAKE_BUILD_TYPE=RELEASE
#    - OS_TYPE=win32
# etc

notifications:
  email: false

services:
  - docker

before_install:
  - docker pull tangocs/mysql:9.2.2
  - docker pull tangocs/tango-cs:latest
  - git clone https://github.com/JoakimSoderberg/coveralls-cmake.git
  - git clone https://${CI_USER_TOKEN}@github.com/tango-controls/tango-idl.git idl
  - chmod +x .travis/run.sh

before_script:
  - docker run --name mysql_db -e MYSQL_ROOT_PASSWORD=root -d tangocs/mysql:9.2.2 --sql-mode=""
  - CONTAINER=$(docker run --name tango_cs -e TANGO_HOST=127.0.0.1:10000 -e MYSQL_HOST=mysql_db:3306 -e MYSQL_USER=tango -e MYSQL_PASSWORD=tango -e MYSQL_DATABASE=tango --link mysql_db:mysql_db -d tangocs/tango-cs:latest)
  - IPADDR=$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' $CONTAINER)
  - TANGO_HOST=${IPADDR}:10000
  - docker build --build-arg APP_UID=$(id -u) --build-arg APP_GID=$(id -g) -t cpp_tango .travis/${OS_TYPE}
  - docker run --name cpp_tango -e TANGO_HOST=${TANGO_HOST} --link tango_cs:tango_cs -v `pwd`:/home/tango/src -v `pwd`/idl:/home/tango/idl -v `pwd`/coveralls-cmake:/home/tango/coveralls-cmake -dit cpp_tango

script:
  - .travis/run.sh
after-success:
  - test $COVERALLS = "ON" && docker exec cpp_tango /bin/sh -c 'cd /home/tango/src/build; make coveralls'

after-script:
  - docker stop cpp_tango
  - docker rm cpp_tango
  - docker stop tango_cs
  - docker rm tango_cs
  - docker stop mysql_db
  - docker rm mysql_db
